<?php

namespace app\components;
use yii\base\Widget;

class LoginBar extends Widget
{
    public $name;

    public function init(){
        parent::init();
        if (empty($this->name)) $this->name = 'Kkkkkkkk';
    }

    public function run()
    {
        //parent::run(); // TODO: Change the autogenerated stub
        return $this->render('LoginBar',['name' => $this->name]);
    }
}